// Chinese (Simplified) UI text. Keys are the English strings used with t().
export const ZH: Record<string, string> = {
  "New poll": "新建排期",
  "Firebase isn't configured yet. Copy .env.example to .env and fill in your Firebase web config (see README.md). Until then, creating and joining polls won't work.": "Firebase 还没有配置。请把 .env.example 复制为 .env 并填入 Firebase 网页配置（见 README.md）。在此之前无法创建或参与排期。",
  "No sign-up · Share-link only · Your times stay in your timezone": "无需注册 · 分享链接即可 · 时间始终按你的时区显示",
  "Sign-in failed": "登录失败",
  "Optional: keep your polls across devices": "可选：在不同设备上同步你的排期",
  "Sign in with Google": "用 Google 登录",
  "Signed in": "已登录",
  "My schedule": "我的常用时间",
  "Sign out": "退出登录",
  "You": "你",
  "Click or drag across the grid to mark when you're free. Faint blue shows when others are free.": "点击或拖动网格，标出你有空的时间。浅蓝色表示其他人有空。",
  "Click or drag across the grid to mark when you're free.": "点击或拖动网格，标出你有空的时间。",
  "Darker means more people are free. 1 person so far. Hover or tap a slot to see who.": "颜色越深，有空的人越多。目前 1 人回复。悬停或点按时段可查看是谁。",
  "Darker means more people are free. {n} people so far. Hover or tap a slot to see who.": "颜色越深，有空的人越多。目前 {n} 人回复。悬停或点按时段可查看是谁。",
  "No responses yet. The overlap fills in as people mark their times.": "还没有人回复。大家标出时间后，这里会显示重叠情况。",
  "View": "视图",
  "Mark my times": "标记我的时间",
  "See everyone": "查看所有人",
  "You're free": "你有空",
  "If needed": "勉强可以",
  "Others free (faint)": "其他人有空（浅色）",
  "{n} free": "{n} 人有空",
  "Paint as": "标记为",
  "Free": "有空",
  "“If needed” means possible but not ideal. It's used only when no time works for everyone.": "“勉强可以”表示可以但不理想，只有在找不到所有人都有空的时间时才会用到。",
  "{names} free": "{names} 有空",
  "nobody free": "没有人有空",
  "if needed: {names}": "勉强可以：{names}",
  "Hover or tap the grid to see who is free at any time.": "悬停或点按网格，查看任意时段谁有空。",
  "Previous month": "上个月",
  "Next month": "下个月",
  "Days": "日期",
  "Tap once for free, twice for “if needed”": "点一下为有空，点两下为“勉强可以”",
  "Tap the times you're free": "点选你有空的时间",
  "Others free": "其他人有空",
  "Next day": "下一天",
  "12:00 AM (next day)": "24:00（次日）",
  "Poll updated": "排期已更新",
  "Couldn't save: {msg}": "保存失败：{msg}",
  "Edit poll": "编辑排期",
  "Close": "关闭",
  "Meeting name": "会议名称",
  "Respond by (optional)": "回复截止日期（可选）",
  "Who should respond? (optional)": "需要谁回复？（可选）",
  "One name per line, e.g.\nAlex\nMei": "每行一个名字，例如\nAlex\nMei",
  "With names listed, the dashboard shows who hasn't responded yet (matched by the name they enter).": "填写名字后，总览会显示还有谁没回复（按对方填写的名字匹配）。",
  "Days of the week": "星期几",
  "Selected · {n}": "已选 · {n}",
  "Remove {name}": "移除 {name}",
  "From": "从",
  "To": "到",
  "The end time needs to be after the start time.": "结束时间需要晚于开始时间。",
  "1 person has already answered. Their marks stay for times you keep; times you remove are dropped, and new times start empty, so you may want to ask them to check again.": "已有 1 人回复。保留的时间段会保留对方的标记；删掉的时间段会被移除，新增的时间段是空的，你可能需要请对方再确认一次。",
  "{n} people have already answered. Their marks stay for times you keep; times you remove are dropped, and new times start empty, so you may want to ask them to check again.": "已有 {n} 人回复。保留的时间段会保留大家的标记；删掉的时间段会被移除，新增的时间段是空的，你可能需要请大家再确认一次。",
  "Cancel": "取消",
  "Saving…": "正在保存…",
  "Save changes": "保存修改",
  "on a Mac, set one in Mail → Settings → General → “Default email reader.”": "在 Mac 上，可在“邮件 → 设置 → 通用 → 默认电子邮件阅读器”中设置。",
  "on Windows, set one in Settings → Apps → Default apps → Email.": "在 Windows 上，可在“设置 → 应用 → 默认应用 → 电子邮件”中设置。",
  "on iPhone/iPad, set a default in Settings → Apps → Mail → Default Mail App.": "在 iPhone/iPad 上，可在“设置 → App → 邮件 → 默认邮件 App”中设置。",
  "on Android, pick a default in Settings → Apps → Default apps.": "在 Android 上，可在“设置 → 应用 → 默认应用”中选择。",
  "set a default email app in your system settings.": "请在系统设置中指定默认邮件应用。",
  "Calendar file downloaded": "日历文件已下载",
  "Draft email": "邮件草稿",
  "Email language": "邮件语言",
  "Template (by meeting type)": "模板（按会议类型）",
  "Subject": "主题",
  "Subject copied": "主题已复制",
  "Copy": "复制",
  "Body": "正文",
  "Email copied — paste it into any email": "邮件已复制，可粘贴到任何邮件里",
  "Copy email to clipboard": "复制邮件",
  "Works on any device — paste into Gmail, Outlook, Apple Mail, or whatever you use.": "任何设备都能用：粘贴到 Gmail、Outlook、Apple 邮件或你常用的邮箱。",
  "Or open a ready-made draft in": "或者直接打开草稿：",
  "Opening your email app… if nothing happens, no default email app is set — copy the email or use Gmail/Outlook instead.": "正在打开邮件应用… 如果没有反应，说明没有设置默认邮件应用，请复制邮件或改用 Gmail/Outlook。",
  "Mail app": "邮件应用",
  "Recipients prefilled from 1 shared email: {list}": "已根据 1 个邮箱预填收件人：{list}",
  "Recipients prefilled from {n} shared emails: {list}": "已根据 {n} 个邮箱预填收件人：{list}",
  "No participant emails collected, so the “To” field is left blank — add recipients yourself.": "没有收集到参与者的邮箱，所以收件人为空，请自己填写。",
  "Gmail and Outlook open in your browser and work on any computer. “Mail app” opens your device’s default email program — {tip} If nothing opens, just copy the email above.": "Gmail 和 Outlook 在浏览器中打开，任何电脑都能用。“邮件应用”会打开设备的默认邮件程序——{tip} 如果没有打开，直接复制上面的邮件即可。",
  "Add to everyone’s calendar": "加到所有人的日历",
  "Download calendar file (.ics)": "下载日历文件（.ics）",
  "Opens in Apple Calendar, Google Calendar, Outlook and more. Attach it to the email so guests add it in one click — it shows in each person’s own timezone and repeats weekly.": "可在 Apple 日历、Google 日历、Outlook 等中打开。附在邮件里，参与者一键就能添加；会按每个人自己的时区显示，并每周重复。",
  "Opens in Apple Calendar, Google Calendar, Outlook and more. Attach it to the email so guests add it in one click — it shows in each person’s own timezone.": "可在 Apple 日历、Google 日历、Outlook 等中打开。附在邮件里，参与者一键就能添加；会按每个人自己的时区显示。",
  "{n}/{total} free": "{n}/{total} 人有空",
  "QR code for the invite link": "邀请链接的二维码",
  "Scan to open the invite on a phone. Handy for a slide, a printout or someone in the room.": "用手机扫码打开邀请。适合放在幻灯片、打印件上，或给在场的人扫。",
  "Download PNG": "下载 PNG",
  "{n} of {total} free": "{total} 人中 {n} 人有空",
  "{n} sessions": "{n} 次",
  "must attend": "必须参加",
  "if needed": "勉强可以",
  "Late night for {names}": "对 {names} 来说是深夜",
  "Outside work hours for {names}": "对 {names} 来说是非工作时间",
  "{names} would use a time marked “if needed”.": "{names} 需要用到标为“勉强可以”的时间。",
  "{names} would use times marked “if needed”.": "{names} 需要用到标为“勉强可以”的时间。",
  "{names} can't make every session": "{names} 无法参加每一次",
  "{names} can't make it": "{names} 来不了",
  "Picked": "已选定",
  "Pick these times": "选定这些时间",
  "Pick this time": "选定这个时间",
  "Recommended · everyone can make it": "推荐 · 所有人都有空",
  "No single time fits everyone for the full meeting. Here are the closest options.": "没有一个时间能让所有人完整参加，下面是最接近的选项。",
  "Same times every week?": "每周时间都差不多？",
  "to save your usual schedule and fill any poll in one click.": "后可以保存常用时间，在任何排期里一键填入。",
  "Save your usual weekly times once, then fill any poll in one click.": "设置一次每周常用时间，以后任何排期都能一键填入。",
  "Set up my schedule": "设置常用时间",
  "Fill from my schedule": "用常用时间填入",
  "Filled 1 slot. Adjust anything that's different this time.": "已填入 1 个时段。这次有不同的地方可以再调整。",
  "Filled {n} slots. Adjust anything that's different this time.": "已填入 {n} 个时段。这次有不同的地方可以再调整。",
  "Your usual schedule doesn't overlap this poll's times.": "你的常用时间和这个排期的时间没有重叠。",
  "Undo": "撤销",
  "Replaces what's marked here with your usual times.": "会用你的常用时间替换这里已标记的内容。",
  "Edit schedule": "编辑常用时间",
  "No matching timezone": "没有匹配的时区",
  "Your polls": "我的排期",
  "Untitled poll": "未命名排期",
  "Remove {name} from this list": "从列表中移除 {name}",
  "Remove from this list (doesn't delete the poll)": "从列表中移除（不会删除排期）",
  "Saved in this browser and under your account. Removing one here doesn't delete the poll.": "保存在这个浏览器和你的账号下。在这里移除不会删除排期。",
  "Saved in this browser. Removing one here doesn't delete the poll.": "保存在这个浏览器里。在这里移除不会删除排期。",
  "very early": "太早",
  "late night": "深夜",
  "early morning": "清晨",
  "evening": "晚上",
  "No responses yet": "还没有人回复",
  "Wait for participants to submit their availability first.": "请先等参与者提交时间。",
  "Only {n} of {total} sessions fit with everyone free": "{total} 次中只有 {n} 次能让所有人都有空",
  "There aren't enough separate windows where all participants overlap. Consider fewer sessions per week, a shorter duration, or excluding someone (see below).": "所有人都有空的时间段不够多。可以考虑减少每周次数、缩短时长，或排除某个人（见下方）。",
  "Everyone fits with “if needed” times": "算上“勉强可以”的时间，所有人都能参加",
  "No {d}-min window has everyone fully free, but it works if one person uses times they marked “if needed”.": "没有一个 {d} 分钟的时段让所有人都完全有空，但如果有 1 人用上标为“勉强可以”的时间就可以。",
  "No {d}-min window has everyone fully free, but it works if {n} people use times they marked “if needed”.": "没有一个 {d} 分钟的时段让所有人都完全有空，但如果有 {n} 人用上标为“勉强可以”的时间就可以。",
  "Works for everyone required": "所有必须参加的人都有空",
  "The required person is free; {best} of {total} overall.": "必须参加的人有空；总共 {total} 人中 {best} 人有空。",
  "All {n} required people are free; {best} of {total} overall.": "{n} 位必须参加的人都有空；总共 {total} 人中 {best} 人有空。",
  "Shorten to {m} min — everyone can make it": "缩短到 {m} 分钟，所有人都能参加",
  "No {d}-min window works for all {total}, but a {m}-min window does.": "没有一个 {d} 分钟的时段适合全部 {total} 人，但 {m} 分钟的时段可以。",
  "Split into {n} shorter sessions across days": "拆成 {n} 次较短的会议，分在不同天",
  "Instead of one {d}-min meeting, run {n} sessions of {m} min on different days — everyone is free for each.": "把一次 {d} 分钟的会议，改成在不同天开 {n} 次、每次 {m} 分钟——每次所有人都有空。",
  "Best partial overlaps": "重叠最多的时段",
  "The strongest {d}-min windows cover {counts} participants.": "最好的 {d} 分钟时段分别覆盖 {counts} 位参与者。",
  "Not enough shared availability": "共同的空闲时间不够",
  "No window fits even a shortened meeting. Ask participants to add more available slots, or widen the candidate dates/hours.": "即使缩短会议也找不到合适的时段。请参与者多标一些时间，或扩大候选日期和时段。",
  "Works if one person steps out": "如果有一人缺席就可以",
  "Excluding one participant opens up the full-length window.": "排除一位参与者后，就有完整时长的时段了。",
  "Create poll & get link": "创建排期并获取链接",
  "Creating…": "正在创建…",
  "Pick at least one day to continue": "请至少选一天",
  "Pick at least one weekday": "请至少选一个星期几",
  "Fix the hours to continue": "请先修正时段",
  "Connecting…": "正在连接…",
  "No days picked yet": "还没有选日期",
  "1 day": "1 天",
  "{n} days": "{n} 天",
  "1 weekday, every week": "每周 1 天",
  "{n} weekdays, every week": "每周 {n} 天",
  "Could not create poll: {msg}": "无法创建排期：{msg}",
  "MeetSpan organizer link": "MeetSpan 发起人链接",
  "Keep this private — it's your key to manage the poll and pick the final time:": "请妥善保管——这是你管理排期、确定最终时间的钥匙：",
  "Participant invite link (this is the one to share):": "参与者邀请链接（分享这个）：",
  "When are you free?": "你什么时候有空？",
  "Mark when you're free (it shows in your own timezone, no sign-up needed):": "标出你有空的时间（按你自己的时区显示，无需注册）：",
  "Your poll is live": "排期已创建",
  "Invite your group": "邀请大家",
  "Anyone with this link can add their times.": "任何拿到这个链接的人都可以填写时间。",
  "Copied": "已复制",
  "Copy link": "复制链接",
  "Share…": "分享…",
  "Email": "邮件",
  "QR code": "二维码",
  "Preview as a guest": "以参与者身份预览",
  "Your private organizer link": "你的私人发起人链接",
  "Keep this one to yourself. It's how you see results and lock in the time. It's saved under “Your polls” in this browser; email it to yourself as a backup (we can't recover it for you).": "这个链接请自己保留。你要靠它查看结果、确定时间。它已保存在这个浏览器的“我的排期”里；建议发邮件给自己备份（丢了我们也找不回来）。",
  "Copy private link": "复制私人链接",
  "Email it to me": "发邮件给自己",
  "Create another poll": "再建一个排期",
  "Skip to the dashboard": "直接去总览",
  "Next: add my own times": "下一步：填写我的时间",
  "No sign-up · Free · Every timezone": "无需注册 · 免费 · 支持所有时区",
  "Find a time that works for everyone": "找到所有人都方便的时间",
  "Pick some days, share one link, and each person marks when they're free in their own timezone. MeetSpan finds the overlap.": "选几天，分享一个链接，每个人按自己的时区标出有空的时间，MeetSpan 帮你找出重叠。",
  "Couldn't sign in. Enable Anonymous sign-in in your Firebase console (Authentication → Sign-in method → Anonymous), then reload.": "无法登录。请在 Firebase 控制台启用匿名登录（Authentication → Sign-in method → Anonymous），然后刷新页面。",
  "The basics": "基本信息",
  "What's the meeting?": "会议名称",
  "e.g. Weekly research sync": "例如：每周研究例会",
  "Your name": "你的名字",
  "Your timezone": "你的时区",
  "Which days?": "选哪几天？",
  "How to pick days": "选择日期的方式",
  "Specific dates": "具体日期",
  "Repeats weekly": "每周重复",
  "Clear": "清空",
  "Click days on the calendar.": "在日历上点选日期。",
  "They'll show up here.": "选中的会显示在这里。",
  "Hold Shift and click a second day to select the whole range in between.": "按住 Shift 再点另一天，可选中中间的整段日期。",
  "For a recurring meeting. Pick the days it can happen; guests see weekday names, not dates.": "用于定期会议。选出可以开会的星期几；参与者看到的是星期几，而不是具体日期。",
  "First week": "第一周",
  "Starting this week": "从本周开始",
  "Week of {date} (next week)": "{date} 那一周（下周）",
  "Week of {date}": "{date} 那一周",
  "First meetings could fall on": "第一次会议可能在",
  "Pick at least one weekday above.": "请在上面至少选一个星期几。",
  "then every week": "之后每周重复",
  "What hours?": "哪些时段？",
  "Custom": "自定义",
  "Set your own": "自己设定",
  "In your timezone. Guests automatically see these hours converted to theirs, in 30-minute blocks.": "按你的时区。参与者看到时会自动换算成他们的时区，以 30 分钟为一格。",
  "Preview": "预览",
  "Your grid appears here once you pick days": "选好日期后，这里会显示网格",
  "+{n} more days": "还有 {n} 天",
  "You'll get a share link plus a private link to manage the poll. No account needed.": "你会得到一个分享链接和一个用来管理排期的私人链接，无需注册账号。",
  "Firebase isn't configured yet (see README).": "Firebase 还没有配置（见 README）。",
  "Save the times you're usually free each week. Then, in any poll, one click fills them in, converted to that poll's timezone.": "保存你每周通常有空的时间。之后在任何排期里一键填入，并自动换算成该排期的时区。",
  "Sign in with Google to start": "用 Google 登录后开始",
  "Your schedule is private. Others only see the times you put into a poll.": "常用时间只有你自己能看到。别人只能看到你填进排期里的时间。",
  "Loading…": "加载中…",
  "Couldn't save": "保存失败",
  "Saved": "已保存",
  "The times you're usually free each week. In any poll, “Fill from my schedule” marks these for you, converted to that poll's timezone.": "你每周通常有空的时间。在任何排期里点“用常用时间填入”，就会自动标好，并换算成该排期的时区。",
  "My timezone": "我的时区",
  "Quick start": "快速设置",
  "Clear all": "全部清空",
  "Click or drag to mark when you're usually free.": "点击或拖动，标出你通常有空的时间。",
  "Show {a} – {b} only": "只显示 {a} – {b}",
  "Show all 24 hours": "显示全天 24 小时",
  "Private to you. Nothing is filled in automatically: in each poll you choose when to use it, and you can still adjust that week.": "只有你能看到。不会自动填入：每个排期里由你决定是否使用，填入后也可以针对那一周再调整。",
  "Setup steps": "设置步骤",
  "Share the invite link": "分享邀请链接",
  "Shared": "已分享",
  "Done when you created the poll. Copy it again from the top right any time.": "创建排期时已完成。随时可以在右上角再次复制。",
  "Add your own times": "填写自己的时间",
  "My times": "我的时间",
  "Saved. Keep adjusting until it's right.": "已保存，可以继续调整。",
  "Optional. Mark them in the grid.": "可选，在网格里标出来即可。",
  "See the dashboard": "查看总览",
  "Dashboard": "总览",
  "Best times and everyone's overlap. It fills in as people respond.": "最佳时间和大家的重叠情况，会随回复自动更新。",
  "Save failed: {msg}": "保存失败：{msg}",
  "Couldn't sign in": "无法登录",
  "Enable Anonymous sign-in in your Firebase console (Authentication → Sign-in method → Anonymous), then reload.": "请在 Firebase 控制台启用匿名登录（Authentication → Sign-in method → Anonymous），然后刷新页面。",
  "Signing you in…": "正在登录…",
  "Poll not found": "找不到这个排期",
  "This link may be wrong or the poll was removed.": "链接可能有误，或排期已被删除。",
  "Your times are saved": "你的时间已保存",
  "Couldn't update: {msg}": "更新失败：{msg}",
  "People": "参与者",
  "{n} of {total} expected": "预计 {total} 人，已回复 {n} 人",
  "Mark who must attend. Suggested times will always include them.": "标出必须参加的人，推荐的时间一定会包含他们。",
  "Must attend": "必须参加",
  "Optional": "可选",
  "Still waiting on": "还在等",
  "Meeting poll": "会议排期",
  "Collecting responses": "正在收集回复",
  "Closed": "已关闭",
  "Your timezone: {zone}": "你的时区：{zone}",
  "Deadline passed {date}": "截止日期已过（{date}）",
  "Respond by {date}": "请在 {date} 前回复",
  "Copy invite link": "复制邀请链接",
  "Show invite QR code": "显示邀请二维码",
  "More actions": "更多操作",
  "Edit poll (name, deadline, days, hours)": "编辑排期（名称、截止日期、日期、时段）",
  "Couldn't update the poll: {msg}": "无法更新排期：{msg}",
  "Close poll": "关闭排期",
  "Reopen poll": "重新开放排期",
  "Edit my times": "编辑我的时间",
  "Add my times": "填写我的时间",
  "You're viewing without the organizer key, so controls are disabled. Open your private organizer link to manage this poll.": "你没有使用发起人链接打开，所以无法操作。请用你的私人发起人链接来管理这个排期。",
  "Your availability": "你的空闲时间",
  "Your times count toward the overlap, just like everyone else's.": "你的时间和其他人一样，会计入重叠结果。",
  "Done, see the dashboard": "完成，查看总览",
  "Only your own times so far. The results fill in by themselves as people respond.": "目前只有你自己的时间。大家回复后，结果会自动更新。",
  "No responses yet. The results fill in by themselves as people respond.": "还没有人回复。大家回复后，结果会自动更新。",
  "Responses": "回复",
  "Best overlap": "最佳重叠",
  "No overlap yet": "暂无重叠",
  "Timezones": "时区",
  "{a} to {b} · {n} hours apart": "{a} 到 {b} · 相差 {n} 小时",
  "Everyone in {city}": "所有人都在 {city}",
  "Locked in: {time}": "已确定：{time}",
  "Send the final time to everyone who left an email, or download a calendar invite.": "把最终时间发给留了邮箱的人，或下载日历邀请。",
  "Email & calendar invite": "邮件和日历邀请",
  "Best times": "最佳时间",
  "Meeting length": "会议时长",
  "Updates live as people respond. Hover a card to see it on the grid.": "随回复实时更新。把鼠标移到卡片上，可在网格中看到对应时段。",
  "Meeting details": "会议详情",
  "e.g. Research sync": "例如：研究例会",
  "Sessions per week": "每周次数",
  "Once": "1 次",
  "{n} times": "{n} 次",
  "Meeting type": "会议类型",
  "Open your private organizer link to pick a time": "请用你的私人发起人链接来选定时间",
  "All times everyone can make it": "所有人都有空的全部时间",
  "Every {d} slot where all {n} people are free, in your timezone. Tick one or more to lock them in.": "所有 {n} 人都有空的每个{d}时段（按你的时区）。勾选一个或多个即可确定。",
  "Tick the times you want": "勾选你想要的时间",
  "Pick 1 selected time": "选定 1 个时间",
  "Pick {n} selected times": "选定 {n} 个时间",
  "Waiting for responses": "等待回复中",
  "Send the invite link to your group. The best times show up here as soon as people mark when they're free.": "把邀请链接发给大家。大家标出有空的时间后，最佳时间会显示在这里。",
  "Add my own times": "填写我的时间",
  "Everyone's availability": "所有人的空闲时间",
  "Our meeting": "我们的会议",
  "{name} (you)": "{name}（你）",
  "This poll needs Anonymous sign-in, which the site owner hasn't enabled yet. Please try again later.": "这个排期需要匿名登录，但网站还没有开启。请稍后再试。",
  "This invite link may be wrong or the poll was removed.": "邀请链接可能有误，或排期已被删除。",
  "{days}, every week": "每周{days}",
  "Meeting": "会议",
  "Mark your free times below": "请在下方标出有空的时间",
  "Add your name to save": "填写名字后才能保存",
  "Saved automatically": "已自动保存",
  "{name} invited you": "{name} 邀请了你",
  "Someone": "有人",
  "1 person has responded": "已有 1 人回复",
  "{n} people have responded": "已有 {n} 人回复",
  "Deadline was {date}": "截止日期是 {date}",
  "Please respond by {date}": "请在 {date} 前回复",
  "The time is set": "时间已确定",
  "in your timezone": "按你的时区",
  "repeats every week": "每周重复",
  "Scheduled with MeetSpan by {name}.": "由 {name} 通过 MeetSpan 安排。",
  "Scheduled with MeetSpan.": "通过 MeetSpan 安排。",
  "Add to Google Calendar": "加到 Google 日历",
  "This poll is closed, so your times are read-only now.": "这个排期已关闭，你的时间现在只能查看。",
  "Responding as": "回复人",
  "Times shown in": "显示时区",
  "Optional, for the final time": "可选，用于接收最终时间",
  "Try again": "重试",
  "Who's free": "谁有空",
  "Same timezone as you": "和你同一时区",
  "{time} in {city}": "{city} 当地 {time}",
  "Busy": "没空",
  "Best 1-hour slot so far": "目前最佳的 1 小时",
  "{n} of {total} people free": "{total} 人中 {n} 人有空",
  "No overlap yet. It shows up as people mark their times.": "暂无重叠。大家标出时间后会显示在这里。",
  "Responded · {n}": "已回复 · {n}",
  "Nobody yet. You could be first.": "还没有人回复，你可以第一个填。",
  "Mon": "周一",
  "Tue": "周二",
  "Wed": "周三",
  "Thu": "周四",
  "Fri": "周五",
  "Sat": "周六",
  "Sun": "周日",
  "Su": "日",
  "Mo": "一",
  "Tu": "二",
  "We": "三",
  "Th": "四",
  "Fr": "五",
  "Sa": "六",
  "Work hours": "工作时间",
  "Mornings": "上午",
  "Afternoons": "下午",
  "Evenings": "晚上",
  "30 min": "30 分钟",
  "1 hr": "1 小时",
  "1.5 hr": "1.5 小时",
  "2 hr": "2 小时",
  "Weekdays 9–5": "工作日 9–17 点",
  "Weekday mornings": "工作日上午",
  "Weekday evenings": "工作日晚上",
  "Team sync / recurring": "团队例会 / 定期会议",
  "1:1 / mentor meeting": "一对一 / 导师会面",
  "Study group / seminar": "学习小组 / 研讨会",
  "Interview / client call": "面试 / 客户通话",
  "Common": "常用",
  "Americas": "美洲",
  "Europe": "欧洲",
  "Africa": "非洲",
  "Asia": "亚洲",
  "Australia": "澳大利亚",
  "Pacific": "太平洋",
  "Atlantic": "大西洋",
  "Indian Ocean": "印度洋",
  "Antarctica": "南极洲",
  "Arctic": "北极",
  "Other": "其他",
};
