// Writes src/lib/tzZh.ts: the Chinese city name for every IANA timezone, from
// Unicode CLDR (the data browsers and operating systems use), plus its license.
// Run with: node scripts/generate-tz-zh.mjs [cldr-version]
import { writeFileSync } from "node:fs";

const version = process.argv[2] ?? "48.2.0";
const base = `https://cdn.jsdelivr.net/npm/cldr-dates-full@${version}`;

const res = await fetch(`${base}/main/zh/timeZoneNames.json`);
if (!res.ok) throw new Error(`CLDR download failed: ${res.status}`);
const zones = (await res.json()).main.zh.dates.timeZoneNames.zone;

const names = {};
(function walk(node, path) {
  for (const [k, v] of Object.entries(node)) {
    if (v && typeof v === "object" && typeof v.exemplarCity === "string") names[[...path, k].join("/")] = v.exemplarCity;
    else if (v && typeof v === "object") walk(v, [...path, k]);
  }
})(zones, []);

const ids = Object.keys(names).sort();
const lines = ids.map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(names[id])},`);
writeFileSync(
  "src/lib/tzZh.ts",
  `// Generated by scripts/generate-tz-zh.mjs from Unicode CLDR ${version} (cldr-dates-full).\n` +
    `// Chinese city names for IANA timezones. Do not edit by hand. License: src/lib/tzZh.LICENSE.txt\n` +
    `export const TZ_ZH: Record<string, string> = {\n${lines.join("\n")}\n};\n`
);

const lic = await fetch(`${base}/LICENSE`);
if (!lic.ok) throw new Error(`CLDR license download failed: ${lic.status}`);
writeFileSync("src/lib/tzZh.LICENSE.txt", (await lic.text()).trim() + "\n");
console.log(`Wrote src/lib/tzZh.ts (${ids.length} zones) and its license`);
